export interface AITool {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory: string;
  url: string;
  pricing: 'Free' | 'Freemium' | 'Paid' | 'Enterprise';
  rating: number;
  features: string[];
  useCase: string;
  pros: string[];
  cons: string[];
  tags: string[];
  imageUrl?: string;
  affiliateStatus?: string; // Add this
  affiliateLink?: string;   // Add this
}

export const aiTools: AITool[] = [
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice synthesis and cloning platform',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    url: 'https://elevenlabs.io',
    pricing: 'Freemium',
    rating: 4.7,
    features: ['Voice cloning', 'Text-to-speech', 'Voice design', 'Multi-language'],
    useCase: 'Podcasts, audiobooks, video narration, voiceovers',
    pros: ['Exceptional voice quality', 'Voice cloning', 'Multiple languages', 'API access'],
    cons: ['Expensive for high usage', 'Ethical concerns', 'Limited free tier'],
    tags: ['Voice Synthesis', 'Voice Cloning', 'Text-to-Speech', 'High Quality'],
    imageUrl: 'https://logo.clearbit.com/elevenlabs.io',
    affiliateStatus: 'Active',
    affiliateLink: 'https://try.elevenlabs.io/v5c39ipm1zah'
  },
  {
  id: 'beehiiv',
  name: 'Beehiiv',
  description: 'Newsletter platform with growth tools and analytics',
  category: 'Marketing',
  subcategory: 'Email Marketing',
  url: 'https://beehiiv.com',
  pricing: 'Freemium',
  rating: 4.4,
  features: ['Newsletter creation', 'Audience analytics', 'Monetization', 'Growth tools'],
  useCase: 'Newsletter publishing, audience growth, content monetization',
  pros: ['Modern interface', 'Good analytics', 'Built-in monetization'],
  cons: ['Newer platform', 'Limited integrations'],
    imageUrl: 'https://logo.clearbit.com/beehiiv.com',
  tags: ['Newsletter', 'Email', 'Subscribers'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://www.beehiiv.com?via=Andrew-Mudd'
},
{
  id: 'instantly',
  name: 'Instantly',
  description: 'AI-powered cold email outreach platform',
  category: 'Sales & Marketing',
  subcategory: 'Email Outreach',
  url: 'https://instantly.ai',
  pricing: 'Paid',
  rating: 4.3,
  features: ['Email automation', 'AI personalization', 'Email warmup', 'Analytics'],
  useCase: 'Cold email campaigns, lead generation, sales outreach',
  pros: ['Good deliverability', 'Easy to use', 'Effective warmup'],
    imageUrl: 'https://logo.clearbit.com/instantly.ai',
  cons: ['Limited to email outreach', 'Can be expensive'],
  tags: ['Email', 'Outreach', 'Sales'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://instantly.ai/?via=Growai'
},
{
  id: 'captions-ai',
  name: 'Captions AI',
  description: 'AI-powered video captioning and editing platform',
  category: 'Video & Visual',
  subcategory: 'Video Editing',
  url: 'https://captions.ai',
  pricing: 'Freemium',
  rating: 4.2,
  features: ['AI captions', 'Video editing', 'Voice enhancement', 'Multi-language'],
    imageUrl: 'https://logo.clearbit.com/captions.ai',
  useCase: 'Video captioning, social media content, accessibility',
  pros: ['Easy captioning', 'Good AI accuracy', 'Multiple languages'],
  cons: ['Limited editing features', 'Mobile-focused'],
  tags: ['Video', 'Captions', 'Accessibility'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://capcutaffiliateprogram.pxf.io/o4Wgko'
},
{
  id: 'pandadoc',
  name: 'PandaDoc',
  description: 'AI-powered document creation and e-signature platform',
  category: 'Business & Productivity',
  subcategory: 'Document Management',
  url: 'https://pandadoc.com',
  pricing: 'Freemium',
  rating: 4.4,
  features: ['Document templates', 'E-signatures', 'AI assistance', 'Workflow automation'],
  useCase: 'Proposal creation, contract management, document signing',
  pros: ['Good templates', 'Easy signing', 'Workflow automation'],
    imageUrl: 'https://logo.clearbit.com/pandadoc.com',
  cons: ['Can be expensive', 'Learning curve'],
  tags: ['Documents', 'E-signature', 'Templates'],
  affiliateStatus: 'Application Submitted on Partnerstack.com'
},
{
  id: 'lemonsqueezy',
  name: 'Lemon Squeezy',
  description: 'AI-powered payment processing and e-commerce platform',
  category: 'Business & Productivity',
  subcategory: 'E-commerce',
  url: 'https://lemonsqueezy.com',
  pricing: 'Freemium',
     imageUrl: 'https://logo.clearbit.com/lemonsqueezy.com',
  rating: 4.5,
  features: ['Payment processing', 'Subscription management', 'Tax compliance', 'Analytics'],
  useCase: 'Digital product sales, subscription management, payment processing',
  pros: ['Easy setup', 'Good compliance', 'Global payments'],
  cons: ['Transaction fees', 'Limited customization'],
  tags: ['Payments', 'E-commerce', 'Subscriptions'],
  affiliateStatus: 'Application submitted through their website'
},
{
  id: 'screen-studio',
  name: 'Screen Studio',
  description: 'AI-powered screen recording and video creation tool',
  category: 'Video & Visual',
  subcategory: 'Screen Recording',
     imageUrl: 'https://logo.clearbit.com/screen.studio',
  url: 'https://screen.studio',
  pricing: 'Paid',
  rating: 4.6,
  features: ['Screen recording', 'AI editing', 'Cursor effects', 'Voiceover'],
  useCase: 'Tutorial creation, product demos, educational content',
  pros: ['High-quality recordings', 'Easy editing', 'Professional results'],
  cons: ['Mac only', 'Paid software'],
  tags: ['Screen Recording', 'Tutorials', 'Demo'],
  affiliateStatus: 'Waiting for lemonsqueezy approval'
},
{
"id": "heyreach",
"name": "HeyReach",
"description": "AI-powered outreach and sales automation platform",
"category": "Sales & Marketing",
"subcategory": "Outreach Automation",
"imageUrl": "https://logo.clearbit.com/heyreach.io",
"url": "https://heyreach.io/?via=growai",
"pricing": "Freemium",
"rating": 4.4,
"features": ["AI-powered messaging", "Multi-channel outreach", "Lead management", "Analytics"],
"useCase": "Sales outreach, lead generation, cold email campaigns",
"pros": ["Easy to use", "Multi-channel", "AI optimization"],
"cons": ["Learning curve", "Limited free tier"],
"tags": ["Sales", "Outreach", "Automation", "Email"],
"affiliateStatus": "Active"
},
{
  id: 'deel',
  name: 'Deel',
  description: 'AI-powered global payroll and compliance platform',
  category: 'Business & Productivity',
  subcategory: 'HR & Payroll',
  url: 'https://deel.com',
     imageUrl: 'https://logo.clearbit.com/deel.com',
  pricing: 'Paid',
  rating: 4.5,
  features: ['Global payroll', 'Compliance management', 'Contractor management', 'AI insights'],
  useCase: 'Global hiring, payroll management, compliance',
  pros: ['Global compliance', 'Easy payments', 'Good support'],
  cons: ['Can be expensive', 'Complex for small teams'],
  tags: ['Payroll', 'HR', 'Global'],
  affiliateStatus: 'Application Submitted on Partnerstack.com'
},
{
  id: 'hyperwrite',
  name: 'HyperWrite',
  description: 'AI writing assistant with advanced content generation',
  category: 'Content Generation',
  subcategory: 'Copywriting',
  url: 'https://hyperwrite.ai',
  pricing: 'Freemium',
  rating: 4.2,
  features: ['Content generation', 'Writing assistance', 'Templates', 'Research tools'],
       imageUrl: 'https://logo.clearbit.com/hyperwrite.ai',
  useCase: 'Content creation, writing assistance, research',
  pros: ['Good writing quality', 'Research capabilities', 'Easy to use'],
  cons: ['Limited free tier', 'Can be slow'],
  tags: ['Writing', 'Content', 'Research'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://capcutaffiliateprogram.pxf.io/o4Wgko'
},
 {
    id: 'talkiq',
    name: 'TalkIQ',
    description: 'AI-powered conversation intelligence platform',
    category: 'Audio & Voice',
    subcategory: 'Conversation AI',
    url: 'https://dev.talkiq.ai',
     imageUrl: '/talkiqw.png',
    pricing: 'Enterprise',
    rating: 4.0,
    features: ['Conversation analysis', 'Speech recognition', 'AI insights', 'Performance tracking'],
    useCase: 'Sales call analysis, customer service optimization, conversation intelligence',
    pros: ['Good insights', 'Accurate transcription', 'Useful analytics'],
    cons: ['Expensive', 'Enterprise focused'],
    tags: ['Conversation AI', 'Speech', 'Analytics'],
    affiliateStatus: 'No Affiliate'
  },
{
  id: 'tugan',
  name: 'Tugan',
  description: 'AI-powered content generation and optimization tool',
  category: 'Content Generation',
  subcategory: 'Copywriting',
  url: 'https://tugan.ai',
  pricing: 'Freemium',
  rating: 4.1,
   imageUrl: 'https://logo.clearbit.com/tugan.ai',
  features: ['Content generation', 'SEO optimization', 'Content ideas', 'Multi-format'],
  useCase: 'Content creation, SEO optimization, marketing copy',
  pros: ['SEO focused', 'Multiple formats', 'Easy to use'],
  cons: ['Limited features', 'Newer tool'],
  tags: ['SEO', 'Content', 'Marketing'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://www.tugan.ai/?via=growai'
},
{
  id: 'makeugc',
  name: 'MakeUGC',
  description: 'AI-powered user-generated content creation platform',
  category: 'Video & Visual',
  subcategory: 'UGC Creation',
  url: 'https://makeugc.ai',
  pricing: 'Freemium',
  rating: 4.3,
  features: ['UGC templates', 'AI avatars', 'Voice generation', 'Customization'],
  useCase: 'User-generated content, social media ads, testimonials',
    imageUrl: '/makeugc.png',
  pros: ['Easy UGC creation', 'Good templates', 'Affordable'],
  cons: ['Limited customization', 'New platform'],
  tags: ['UGC', 'Social Media', 'Content'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://www.makeugc.ai/?ref=growai'
},
{
  id: 'soundraw',
  name: 'SoundRaw',
  description: 'AI-powered music generation platform',
  category: 'Audio & Voice',
  subcategory: 'Music Generation',
  url: 'https://soundraw.io',
  pricing: 'Freemium',
  rating: 4.4,
  features: ['AI music generation', 'Customization', 'Royalty-free', 'Multiple genres'],
  useCase: 'Background music, content creation, royalty-free music',
  pros: ['Royalty-free', 'Easy customization', 'Good quality'],
    imageUrl: 'https://logo.clearbit.com/soundraw.io',
  cons: ['Limited complexity', 'AI-generated sound'],
  tags: ['Music', 'Audio', 'Royalty-free'],
  affiliateStatus: 'Application submitted on https://affiliates.soundraw.io/'
},
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Workflow automation platform with AI capabilities',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://n8n.io',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Workflow automation', 'AI integration', 'App connections', 'Custom nodes'],
    useCase: 'Workflow automation, data processing, app integration',
    pros: ['Open source core', 'Powerful automation', 'Extensible'],
      imageUrl: 'https://logo.clearbit.com/n8n.io',
    cons: ['Steep learning curve', 'Technical setup required'],
    tags: ['Automation', 'Workflows', 'Open Source'],
    affiliateStatus: 'Affiliate program currently paused'
  },
  {
    id: 'appolo',
    name: 'Apollo.io',
    description: 'AI-powered sales intelligence and engagement platform',
    category: 'Sales & Marketing',
    subcategory: 'Sales Intelligence',
    url: 'https://apollo.io',
    pricing: 'Paid',
    rating: 4.3,
    features: ['Lead generation', 'Sales intelligence', 'Email automation', 'Analytics'],
    useCase: 'B2B sales, lead generation, outreach campaigns',
      imageUrl: 'https://logo.clearbit.com/apollo.io',
    pros: ['Large database', 'Good analytics', 'Effective outreach'],
    cons: ['Expensive', 'Data accuracy varies'],
    tags: ['Sales', 'Lead Generation', 'B2B'],
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'manychat',
    name: 'ManyChat',
    description: 'AI-powered chatbot platform for messaging apps',
    category: 'Sales & Marketing',
    subcategory: 'Chatbots',
    url: 'https://manychat.com',
    pricing: 'Freemium',
    rating: 4.2,
         imageUrl: 'https://logo.clearbit.com/manychat.com',
    features: ['Chatbot builder', 'Messaging automation', 'AI responses', 'Multi-platform'],
    useCase: 'Customer service, marketing automation, lead generation',
    pros: ['Easy to use', 'Good templates', 'Multi-platform'],
    cons: ['Limited advanced features', 'Can be expensive'],
    tags: ['Chatbots', 'Messaging', 'Automation'],
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'miro',
    name: 'Miro',
    description: 'AI-powered collaborative whiteboard platform',
    category: 'Business & Productivity',
    subcategory: 'Collaboration',
    url: 'https://miro.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['Whiteboarding', 'AI templates', 'Real-time collaboration', 'Integrations'],
      imageUrl: 'https://logo.clearbit.com/miro.com',
    useCase: 'Brainstorming, planning, diagramming, team collaboration',
    pros: ['Excellent collaboration', 'Good templates', 'Easy to use'],
    cons: ['Can be expensive', 'Limited offline functionality'],
    tags: ['Whiteboard', 'Collaboration', 'Visual'],
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'webflow',
    name: 'Webflow',
    description: 'AI-powered web design and development platform',
    category: 'Business & Productivity',
    subcategory: 'Web Development',
    url: 'https://webflow.com',
    pricing: 'Freemium',
    rating: 4.5,
      imageUrl: 'https://logo.clearbit.com/webflow.com',
    features: ['Visual web design', 'AI assistance', 'CMS', 'E-commerce'],
    useCase: 'Website building, web design, content management',
    pros: ['Visual design', 'No code needed', 'Powerful CMS'],
    cons: ['Steep learning curve', 'Expensive'],
    tags: ['Web Design', 'No Code', 'CMS'],
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    description: 'AI-powered note-taking and research assistant',
    category: 'Research & Analysis',
    subcategory: 'Note Taking',
    url: 'https://notebooklm.google.com',
    pricing: 'Free',
      imageUrl: '/nllm.png',
    rating: 4.1,
    features: ['Note organization', 'AI research', 'Document analysis', 'Knowledge synthesis'],
    useCase: 'Research, note-taking, knowledge management',
    pros: ['Google integration', 'Good organization', 'Free'],
    cons: ['Limited features', 'New product'],
    tags: ['Note Taking', 'Research', 'Google'],
    affiliateStatus: 'No Affiliate'
  },
  {
    id: 'lindy',
    name: 'Lindy AI',
    description: 'AI-powered business automation and assistant platform',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://lindy.ai',
    pricing: 'Paid',
    rating: 4.2,
         imageUrl: 'https://cdn.brandfetch.io/idVWnbyH38/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1753167053115',
    features: ['Business automation', 'AI assistant', 'Task management', 'Workflow automation'],
    useCase: 'Business automation, task management, workflow optimization',
    pros: ['Good automation', 'Easy setup', 'Time saving'],
    cons: ['Limited integrations', 'New platform'],
    tags: ['Automation', 'Assistant', 'Business'],
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
 
  {
    id: 'paradigm',
    name: 'Paradigm',
    description: 'AI-powered trading and investment platform',
    category: 'Business & Productivity',
    subcategory: 'Finance',
    url: 'https://paradigm.xyz',
    pricing: 'Enterprise',
    rating: 4.3,
    features: ['Trading algorithms', 'AI analysis', 'Market insights', 'Risk management'],
      imageUrl: 'https://logo.clearbit.com/paradigm.xyz',
    useCase: 'Algorithmic trading, investment analysis, market research',
    pros: ['Powerful analysis', 'Good insights', 'Professional tools'],
    cons: ['Complex', 'Enterprise focused'],
    tags: ['Trading', 'Finance', 'Investment'],
    affiliateStatus: 'No affiliate'
  },
  {
    id: 'semrush',
    name: 'SemRush',
    description: 'AI-powered SEO and digital marketing platform',
    category: 'Sales & Marketing',
    subcategory: 'SEO',
    url: 'https://semrush.com',
    pricing: 'Paid',
       imageUrl: 'https://logo.clearbit.com/semrush.com',
    rating: 4.6,
    features: ['SEO analysis', 'Keyword research', 'Competitor analysis', 'Content optimization'],
    useCase: 'SEO, digital marketing, content strategy, competitor analysis',
    pros: ['Comprehensive SEO tools', 'Good data', 'Extensive features'],
    cons: ['Expensive', 'Complex interface'],
    tags: ['SEO', 'Digital Marketing', 'Analytics'],
    affiliateStatus: 'Application pending'
  },
{
  id: 'taplio',
  name: 'Taplio',
  description: 'AI-powered LinkedIn content creation and analytics',
  category: 'Content Generation',
  subcategory: 'Social Media',
     imageUrl: 'https://logo.clearbit.com/taplio.com',
  url: 'https://taplio.com',
  pricing: 'Freemium',
  rating: 4.5,
  features: ['LinkedIn analytics', 'Content ideas', 'Scheduling', 'AI writing'],
  useCase: 'LinkedIn marketing, content scheduling, audience growth',
  pros: ['LinkedIn focused', 'Good analytics', 'Content ideas'],
  cons: ['LinkedIn only', 'Can be expensive'],
  tags: ['LinkedIn', 'Social Media', 'Analytics'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://taplio.com/?via=growai'
},
{
  id: 'lovable',
  name: 'Lovable',
  description: 'AI-powered customer feedback and feature request platform',
  category: 'Business & Productivity',
  subcategory: 'Customer Feedback',
  url: 'https://lovable.dev',
  pricing: 'Freemium',
  rating: 4.3,
  features: ['Feedback management', 'Feature voting', 'User insights', 'AI analysis'],
    imageUrl: 'https://cdn.brandfetch.io/idH9OjyiUq/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1748239860810',
  useCase: 'Product feedback, feature prioritization, customer insights',
  pros: ['Easy feedback collection', 'Good analysis', 'User-friendly'],
  cons: ['Limited integrations', 'New platform'],
  tags: ['Feedback', 'Product', 'Customers'],
  affiliateStatus: 'Active',
  affiliateLink: 'https://lovable.dev/?via=grow-ai'
},
  {
    id: 'surfer',
    name: 'Surfer SEO',
    description: 'AI-powered SEO content optimization and keyword research',
    category: 'Content Generation',
    subcategory: 'SEO',
    url: 'https://surferseo.com',
    pricing: 'Paid',
    rating: 4.6,
    features: ['Content optimization', 'Keyword research', 'SERP analysis', 'Content editor'],
    useCase: 'SEO content creation, keyword optimization, content planning',
    pros: ['Excellent SEO insights', 'Content optimization', 'Data-driven'],
    cons: ['Expensive', 'SEO-focused only'],
    tags: ['SEO', 'Content Optimization', 'Keyword Research'],
    imageUrl: 'https://logo.clearbit.com/surferseo.com',
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI video generation platform with talking avatars and voice cloning',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://heygen.com',
    pricing: 'Paid',
    rating: 4.6,
    features: ['Talking avatars', 'Voice cloning', 'Video templates', 'Multi-language'],
    useCase: 'Marketing videos, presentations, educational content, UGC',
    pros: ['High-quality avatars', 'Voice cloning', 'Easy to use', 'Professional results'],
    cons: ['Expensive', 'Limited avatar customization', 'Watermark on free tier'],
    tags: ['Video Generation', 'AI Avatars', 'Voice Cloning', 'UGC'],
    imageUrl: 'https://logo.clearbit.com/heygen.com',
    affiliateStatus: 'Application submitted through their google form'
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'AI-powered video editing and generation platform',
    category: 'Video & Visual',
    subcategory: 'Video Editing',
    url: 'https://runwayml.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['Video editing', 'AI generation', 'Motion graphics', 'Collaboration'],
    useCase: 'Video editing, motion graphics, AI video generation',
    pros: ['Professional features', 'AI integration', 'Collaboration tools'],
    cons: ['Steep learning curve', 'Expensive', 'Complex'],
    tags: ['Video Editing', 'Motion Graphics', 'Professional'],
    imageUrl: 'https://logo.clearbit.com/runwayml.com',
    affiliateStatus: 'Application submitted through their google form'
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Design platform with AI-powered features',
    category: 'Video & Visual',
    subcategory: 'Design',
    url: 'https://canva.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['AI design tools', 'Templates', 'Collaboration', 'Brand kit'],
    useCase: 'Graphic design, social media, presentations, marketing materials',
    pros: ['Easy to use', 'Extensive templates', 'AI features', 'Collaboration'],
    cons: ['Limited advanced features', 'Template-dependent', 'Can be expensive'],
    tags: ['Design', 'Templates', 'Collaboration', 'AI Design'],
    imageUrl: 'https://logo.clearbit.com/canva.com',
    affiliateStatus: 'Affiliate program currently being restructured'
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'AI-powered writing assistant and grammar checker',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://grammarly.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Grammar checking', 'Writing suggestions', 'Tone analysis', 'Plagiarism detection'],
    useCase: 'Writing improvement, content editing, professional communication',
    pros: ['Excellent grammar checking', 'Writing suggestions', 'Browser integration'],
    cons: ['Expensive premium', 'Privacy concerns', 'Limited creative features'],
    tags: ['Grammar', 'Writing Assistant', 'Editing'],
    imageUrl: 'https://logo.clearbit.com/grammarly.com',
    affiliateStatus: 'Application submitted through impact.com'
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered search engine with real-time information and citations',
    category: 'Language Models',
    subcategory: 'AI Search',
    url: 'https://perplexity.ai',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Real-time search', 'Citations', 'Multiple sources', 'Conversational search'],
    useCase: 'Research, fact-checking, current events, academic work',
    pros: ['Real-time information', 'Source citations', 'Free tier available'],
    cons: ['Limited creative capabilities', 'Search-focused only'],
    tags: ['Search', 'Citations', 'Real-time'],
    imageUrl: 'https://logo.clearbit.com/perplexity.ai',
    affiliateStatus: 'Application submitted through Dub.co'
  },
  {
    id: 'outreach',
    name: 'Outreach',
    description: 'AI-powered sales engagement platform with automation',
    category: 'Sales & Marketing',
    subcategory: 'Sales Automation',
    url: 'https://outreach.io',
    pricing: 'Enterprise',
    rating: 4.5,
    features: ['Sales automation', 'Email sequences', 'Analytics', 'CRM integration'],
    useCase: 'B2B sales, lead nurturing, sales process automation',
    pros: ['Comprehensive sales platform', 'Excellent analytics', 'Enterprise features'],
    cons: ['Very expensive', 'Complex setup', 'Enterprise-focused'],
    tags: ['Sales Automation', 'B2B', 'Enterprise'],
    imageUrl: 'https://logo.clearbit.com/outreach.io',
    affiliateStatus: 'Application submitted through their website'
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation platform with virtual avatars',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://synthesia.io',
    pricing: 'Paid',
    rating: 4.5,
    features: ['AI avatars', 'Video generation', 'Text-to-speech', 'Custom avatars'],
    useCase: 'Training videos, marketing content, educational videos',
    pros: ['High-quality avatars', 'Easy to use', 'Professional results'],
    cons: ['Expensive', 'Limited customization', 'Avatar-focused'],
    tags: ['Video Generation', 'AI Avatars', 'Training'],
    imageUrl: 'https://logo.clearbit.com/synthesia.io',
    affiliateStatus: 'Application submitted through their website'
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'AI-powered workspace with writing and organization assistance',
    category: 'Business & Productivity',
    subcategory: 'Workspace',
    url: 'https://notion.so',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['AI writing', 'Task management', 'Knowledge base', 'Collaboration'],
    useCase: 'Project management, documentation, team collaboration',
    pros: ['Versatile workspace', 'Excellent AI features', 'Great collaboration'],
    cons: ['Can be complex', 'AI features are paid'],
    tags: ['Workspace', 'Collaboration', 'Documentation'],
    imageUrl: 'https://logo.clearbit.com/notion.so',
    affiliateStatus: 'Affiliate program currently paused'
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: 'Visual automation platform with AI-powered workflows',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://make.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Visual automation', 'App integration', 'AI assistance', 'Complex workflows'],
    useCase: 'Complex automation, data processing, business workflows',
    pros: ['Visual interface', 'Complex workflows', 'Good free tier'],
    cons: ['Steep learning curve', 'Can be expensive'],
    tags: ['Visual Automation', 'Complex Workflows', 'Data Processing'],
    imageUrl: 'https://logo.clearbit.com/make.com',
    affiliateStatus: 'Active',
    affiliateLink: 'https://www.make.com/en/register?pc=growaiagency'
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'AI-powered work operating system for teams',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://monday.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Work OS', 'AI automation', 'Team collaboration', 'Custom workflows'],
    useCase: 'Team collaboration, project management, workflow automation',
    pros: ['Comprehensive platform', 'Good automation', 'Customizable'],
    cons: ['Expensive', 'Complex setup', 'Overwhelming features'],
    tags: ['Work OS', 'Collaboration', 'Automation'],
    imageUrl: 'https://logo.clearbit.com/monday.com',
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'AI copywriting tool for marketing, sales, and content creation',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://jasper.ai',
    pricing: 'Paid',
    rating: 4.4,
    features: ['Marketing copy', 'Blog posts', 'Social media', 'Email campaigns'],
    useCase: 'Marketing copy, content creation, brand voice consistency',
    pros: ['Excellent for marketing', 'Brand voice training', 'Templates'],
    cons: ['Expensive', 'Limited to content creation'],
    tags: ['Copywriting', 'Marketing', 'Brand Voice'],
    imageUrl: 'https://logo.clearbit.com/jasper.ai',
    affiliateStatus: 'Affiliate program currently being restructured'
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'AI-powered sales CRM with pipeline management',
    category: 'Sales & Marketing',
    subcategory: 'CRM',
    url: 'https://pipedrive.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Pipeline management', 'AI insights', 'Lead scoring', 'Automation'],
    useCase: 'Sales pipeline management, lead tracking, sales automation',
    pros: ['Easy to use', 'Good pipeline management', 'AI insights'],
    cons: ['Limited features', 'Expensive', 'Basic AI'],
    tags: ['CRM', 'Pipeline Management', 'Sales'],
    imageUrl: 'https://logo.clearbit.com/pipedrive.com',
    affiliateStatus: 'Application Submitted on Partnerstack.com'
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'AI-powered project management and team collaboration',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://asana.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Project management', 'AI insights', 'Team collaboration', 'Workflow automation'],
    useCase: 'Project management, team collaboration, workflow automation',
    pros: ['Excellent project management', 'Good collaboration', 'AI insights'],
    cons: ['Expensive', 'Complex for small teams', 'Limited AI features'],
    tags: ['Project Management', 'Collaboration', 'Workflow'],
    imageUrl: 'https://logo.clearbit.com/asana.com',
    affiliateStatus: 'Application submitted through their website'
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'AI-powered team communication and collaboration platform',
    category: 'Business & Productivity',
    subcategory: 'Workspace',
    url: 'https://slack.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Team messaging', 'AI search', 'App integrations', 'Voice calls'],
    useCase: 'Team communication, collaboration, workflow integration',
    pros: ['Excellent communication', 'Great integrations', 'AI search'],
    cons: ['Expensive', 'Can be distracting', 'Limited AI features'],
    tags: ['Communication', 'Collaboration', 'Integrations'],
    imageUrl: 'https://logo.clearbit.com/slack.com',
    affiliateStatus: 'Application submitted through their website'
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'AI-powered automation platform connecting apps and services',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://zapier.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['App integration', 'Workflow automation', 'AI assistance', 'Triggers'],
    useCase: 'Business automation, app integration, workflow optimization',
    pros: ['Extensive integrations', 'Powerful automation', 'AI assistance'],
    cons: ['Expensive for advanced features', 'Complex for beginners'],
    tags: ['Automation', 'Integrations', 'Workflows'],
    imageUrl: 'https://logo.clearbit.com/zapier.com',
    affiliateStatus: 'Submitted application through their website'
  },
  {
    id: 'capcut',
    name: 'CapCut',
    description: 'Free video editing app with AI-powered features',
    category: 'Video & Visual',
    subcategory: 'Video Editing',
    url: 'https://capcut.com',
    pricing: 'Free',
    rating: 4.4,
    features: ['Video editing', 'AI effects', 'Templates', 'Music library'],
    useCase: 'Social media videos, short-form content, UGC creation',
    pros: ['Completely free', 'Easy to use', 'Good templates', 'AI effects'],
    cons: ['Limited advanced features', 'Mobile-focused', 'Watermark options'],
    tags: ['Video Editing', 'Free', 'Social Media', 'UGC'],
    imageUrl: 'https://logo.clearbit.com/capcut.com',
    affiliateStatus: 'Application submitted through impact.com'
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'Audio and video editing with AI voice generation',
    category: 'Audio & Voice',
    subcategory: 'Audio Editing',
    url: 'https://descript.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['AI voice generation', 'Audio editing', 'Video editing', 'Transcription'],
    useCase: 'Podcasts, videos, presentations, content creation',
    pros: ['Excellent editing tools', 'AI voice features', 'Transcription', 'Easy to use'],
    cons: ['Expensive', 'Complex for beginners', 'Limited free tier'],
    tags: ['Audio Editing', 'AI Voice', 'Transcription', 'Video Editing'],
    imageUrl: 'https://logo.clearbit.com/descript.com',
    affiliateStatus: 'Active',
    affiliateLink: 'https://get.descript.com/dmr7gmw6bd6o'
  }
];