

export interface AITool {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory: string;
  url: string;
  pricing: 'Free' | 'Freemium' | 'Paid' | 'Enterprise';
  rating: number;
  features: string[];
  useCase: string;
  pros: string[];
  cons: string[];
  tags: string[];
    imageUrl?: string; // The '?' makes it optional
}

export const aiTools: AITool[] = [
  // Language Models & AI Assistants
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'Advanced language model for conversation, writing, and problem-solving',
    category: 'Language Models',
    subcategory: 'AI Assistants',
    url: 'https://chat.openai.com',
    pricing: 'Freemium',
    rating: 4.8,
    features: ['Conversational AI', 'Code generation', 'Content writing', 'Problem solving'],
    useCase: 'General AI assistance, content creation, coding help',
    pros: ['Most popular AI tool', 'Extensive knowledge', 'User-friendly interface'],
    cons: ['Limited to 2023 data', 'Can be expensive for heavy usage'],
    tags: ['OpenAI', 'GPT-4', 'Conversational'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png'
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Anthropic\'s AI assistant with strong reasoning and safety focus',
    category: 'Language Models',
    subcategory: 'AI Assistants',
    url: 'https://claude.ai',
    pricing: 'Freemium',
    rating: 4.7,
    features: ['Advanced reasoning', 'Document analysis', 'Code generation', 'Safety-focused'],
    useCase: 'Complex analysis, document processing, ethical AI interactions',
    pros: ['Excellent reasoning', 'Document upload support', 'Safety-conscious'],
    cons: ['Less creative than some alternatives', 'Limited image generation'],
    tags: ['Anthropic', 'Reasoning', 'Safety'],
     imageUrl: 'https://pbs.twimg.com/profile_images/1652431901415395328/IIyKP882_400x400.png'
  },
{
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google\'s multimodal AI model with advanced reasoning capabilities',
    category: 'Language Models',
    subcategory: 'AI Assistants',
    url: 'https://gemini.google.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['Multimodal AI', 'Advanced reasoning', 'Google integration', 'Real-time data'],
    useCase: 'Research, analysis, Google ecosystem integration',
    pros: ['Real-time information', 'Google integration', 'Multimodal capabilities'],
    cons: ['Newer model', 'Limited third-party integrations'],
    tags: ['Google', 'Multimodal', 'Real-time'],
    imageUrl: 'https://logos-world.net/wp-content/uploads/2023/12/Gemini-Symbol.png'
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered search engine with real-time information and citations',
    category: 'Language Models',
    subcategory: 'AI Search',
    url: 'https://perplexity.ai',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Real-time search', 'Citations', 'Multiple sources', 'Conversational search'],
    useCase: 'Research, fact-checking, current events, academic work',
    pros: ['Real-time information', 'Source citations', 'Free tier available'],
    cons: ['Limited creative capabilities', 'Search-focused only'],
    tags: ['Search', 'Citations', 'Real-time'],
    imageUrl: 'https://pbs.twimg.com/profile_images/1664319362959110144/1e5Nt9_1_400x400.jpg'
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'AI copywriting tool for marketing, sales, and content creation',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://jasper.ai',
    pricing: 'Paid',
    rating: 4.4,
    features: ['Marketing copy', 'Blog posts', 'Social media', 'Email campaigns'],
    useCase: 'Marketing copy, content creation, brand voice consistency',
    pros: ['Excellent for marketing', 'Brand voice training', 'Templates'],
    cons: ['Expensive', 'Limited to content creation'],
    tags: ['Copywriting', 'Marketing', 'Brand Voice'],
    imageUrl: 'https://assets-global.website-files.com/5f5d4a1a0c8af1a5bde8b8e5/62a1d5c8d3db1c2c6a5d4e4e_Jasper%20Logo%20Mark%20Color.png'
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: 'AI-powered copywriting platform for businesses and marketers',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://copy.ai',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Marketing copy', 'Product descriptions', 'Social media', 'Email marketing'],
    useCase: 'Quick copy generation, marketing campaigns, product descriptions',
    pros: ['Free tier available', 'Easy to use', 'Quick generation'],
    cons: ['Limited customization', 'Quality varies'],
    tags: ['Copywriting', 'Marketing', 'Quick Generation'],
    imageUrl: 'https://assets-global.website-files.com/63f7b5c4b1f3f954af0e3d4a/63f7b5c4b1f3f9b6a40e3d7b_Copy.ai%20Logo%20-%20Colored%20Text%20with%20Black%20Box.png'
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: 'AI writing assistant for blogs, ads, and marketing content',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://writesonic.com',
    pricing: 'Freemium',
    rating: 4.2,
    features: ['Blog writing', 'Ad copy', 'Landing pages', 'Product descriptions'],
    useCase: 'Content marketing, advertising copy, SEO content',
    pros: ['SEO-focused', 'Multiple content types', 'Affordable'],
    cons: ['Quality can be inconsistent', 'Limited advanced features'],
    tags: ['SEO', 'Content Marketing', 'Affordable'],
    imageUrl: 'https://assets-global.website-files.com/61129a62d4a0d9c9a7a2d3a2/61129a62d4a0d9a1cba2d3e6_Writesonic%20logo%20with%20tagline.png'
  },
  {
    id: 'surfer',
    name: 'Surfer SEO',
    description: 'AI-powered SEO content optimization and keyword research',
    category: 'Content Generation',
    subcategory: 'SEO',
    url: 'https://surferseo.com',
    pricing: 'Paid',
    rating: 4.6,
    features: ['Content optimization', 'Keyword research', 'SERP analysis', 'Content editor'],
    useCase: 'SEO content creation, keyword optimization, content planning',
    pros: ['Excellent SEO insights', 'Content optimization', 'Data-driven'],
    cons: ['Expensive', 'SEO-focused only'],
    tags: ['SEO', 'Content Optimization', 'Keyword Research'],
    imageUrl: 'https://surferseo.com/wp-content/uploads/2022/10/surfer-logo.svg'
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'AI-powered writing assistant and grammar checker',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://grammarly.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Grammar checking', 'Writing suggestions', 'Tone analysis', 'Plagiarism detection'],
    useCase: 'Writing improvement, content editing, professional communication',
    pros: ['Excellent grammar checking', 'Writing suggestions', 'Browser integration'],
    cons: ['Expensive premium', 'Privacy concerns', 'Limited creative features'],
    tags: ['Grammar', 'Writing Assistant', 'Editing'],
    imageUrl: 'https://static.grammarly.com/assets/files/cb6ce17d281d15f2c819035bcd430b0e/grammarly.png'
  },
  {
    id: 'hemingway',
    name: 'Hemingway Editor',
    description: 'AI writing editor for clear, concise content',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://hemingwayapp.com',
    pricing: 'Freemium',
    rating: 4.2,
    features: ['Readability analysis', 'Writing suggestions', 'Style improvement', 'Online editor'],
    useCase: 'Content editing, readability improvement, writing clarity',
    pros: ['Excellent readability analysis', 'Clear suggestions', 'Free web version'],
    cons: ['Limited features', 'Basic AI', 'No advanced editing'],
    tags: ['Readability', 'Writing', 'Editing'],
    imageUrl: 'https://hemingwayapp.com/img/hemingway-icon.png'
  },
  {
    id: 'prowritingaid',
    name: 'ProWritingAid',
    description: 'Comprehensive writing analysis and improvement tool',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://prowritingaid.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Writing analysis', 'Style checking', 'Grammar correction', 'Plagiarism detection'],
    useCase: 'Professional writing, content editing, academic writing',
    pros: ['Comprehensive analysis', 'Style suggestions', 'Multiple integrations'],
    cons: ['Complex interface', 'Expensive', 'Overwhelming features'],
    tags: ['Writing Analysis', 'Style Checking', 'Professional'],
    imageUrl: 'https://prowritingaid.com/images/logo.png'
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    description: 'AI writing assistant for rewriting and improving text',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://wordtune.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Text rewriting', 'Tone adjustment', 'Writing suggestions', 'Browser extension'],
    useCase: 'Content rewriting, tone adjustment, writing improvement',
    pros: ['Excellent rewriting', 'Tone adjustment', 'Easy to use'],
    cons: ['Limited free tier', 'Expensive', 'Browser-dependent'],
    tags: ['Text Rewriting', 'Tone Adjustment', 'Writing'],
    imageUrl: 'https://static.grammarly.com/assets/files/cb6ce17d281d15f2c819035bcd430b0e/wordtune.png'
  },
  {
    id: 'rytr',
    name: 'Rytr',
    description: 'AI writing assistant for various content types',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    url: 'https://rytr.me',
    pricing: 'Freemium',
    rating: 4.1,
    features: ['Content generation', 'Multiple formats', 'Language support', 'Templates'],
    useCase: 'Content creation, marketing copy, blog writing',
    pros: ['Multiple content types', 'Good templates', 'Affordable'],
    cons: ['Quality varies', 'Limited customization', 'Basic features'],
    tags: ['Content Generation', 'Templates', 'Multiple Formats'],
    imageUrl: 'https://rytr.me/public/images/logo.svg'
  },
  {
    id: 'outreach',
    name: 'Outreach',
    description: 'AI-powered sales engagement platform with automation',
    category: 'Sales & Marketing',
    subcategory: 'Sales Automation',
    url: 'https://outreach.io',
    pricing: 'Enterprise',
    rating: 4.5,
    features: ['Sales automation', 'Email sequences', 'Analytics', 'CRM integration'],
    useCase: 'B2B sales, lead nurturing, sales process automation',
    pros: ['Comprehensive sales platform', 'Excellent analytics', 'Enterprise features'],
    cons: ['Very expensive', 'Complex setup', 'Enterprise-focused'],
    tags: ['Sales Automation', 'B2B', 'Enterprise'],
    imageUrl: 'https://outreach.io/wp-content/uploads/2022/05/Outreach-Logo-Full-Color-RGB.svg'
  },
  {
    id: 'hubspot',
    name: 'HubSpot AI',
    description: 'AI-powered CRM and marketing automation platform',
    category: 'Sales & Marketing',
    subcategory: 'CRM',
    url: 'https://hubspot.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['CRM', 'Marketing automation', 'Sales tools', 'AI insights'],
    useCase: 'All-in-one marketing and sales platform',
    pros: ['Comprehensive platform', 'Excellent free tier', 'Great integrations'],
    cons: ['Can be expensive at scale', 'Complex for beginners'],
    tags: ['CRM', 'Marketing Automation', 'All-in-One'],
    imageUrl: 'https://cdn2.hubspot.net/hubfs/HubSpot_Logos/HSLogo_color.svg'
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp AI',
    description: 'AI-powered email marketing and automation platform',
    category: 'Sales & Marketing',
    subcategory: 'Email Marketing',
    url: 'https://mailchimp.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Email automation', 'AI subject lines', 'Segmentation', 'Analytics'],
    useCase: 'Email marketing, customer segmentation, automated campaigns',
    pros: ['User-friendly', 'Excellent free tier', 'Good automation'],
    cons: ['Limited advanced features', 'Can be expensive'],
    tags: ['Email Marketing', 'Automation', 'User-Friendly'],
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968534.png'
  },
  {
    id: 'phrases',
    name: 'Phrases',
    description: 'AI-powered SEO content optimization and keyword research',
    category: 'Sales & Marketing',
    subcategory: 'SEO',
    url: 'https://phrases.io',
    pricing: 'Paid',
    rating: 4.4,
    features: ['Content optimization', 'Keyword research', 'SERP analysis', 'Content briefs'],
    useCase: 'SEO content creation, keyword research, content optimization',
    pros: ['Excellent SEO tools', 'Content optimization', 'Data-driven insights'],
    cons: ['Expensive', 'SEO-focused only'],
    tags: ['SEO', 'Content Optimization', 'Keyword Research'],
    imageUrl: 'https://phrases.io/wp-content/uploads/2022/06/phrases-logo.svg'
  },
  {
    id: 'salesforce',
    name: 'Salesforce Einstein',
    description: 'AI-powered CRM with predictive analytics and automation',
    category: 'Sales & Marketing',
    subcategory: 'CRM',
    url: 'https://salesforce.com',
    pricing: 'Enterprise',
    rating: 4.6,
    features: ['AI predictions', 'Lead scoring', 'Opportunity insights', 'Automation'],
    useCase: 'Enterprise sales, customer relationship management, predictive analytics',
    pros: ['Comprehensive CRM', 'AI predictions', 'Enterprise features'],
    cons: ['Very expensive', 'Complex setup', 'Enterprise-focused'],
    tags: ['CRM', 'Enterprise', 'Predictive Analytics'],
    imageUrl: 'https://logos-world.net/wp-content/uploads/2020/11/Salesforce-Emblem.png'
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'AI-powered sales CRM with pipeline management',
    category: 'Sales & Marketing',
    subcategory: 'CRM',
    url: 'https://pipedrive.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Pipeline management', 'AI insights', 'Lead scoring', 'Automation'],
    useCase: 'Sales pipeline management, lead tracking, sales automation',
    pros: ['Easy to use', 'Good pipeline management', 'AI insights'],
    cons: ['Limited features', 'Expensive', 'Basic AI'],
    tags: ['CRM', 'Pipeline Management', 'Sales'],
    imageUrl: 'https://www.pipedrive.com/themes/custom/pipedrive/logo.svg'
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'AI-powered email marketing and SMS platform',
    category: 'Sales & Marketing',
    subcategory: 'Email Marketing',
    url: 'https://klaviyo.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Email automation', 'SMS marketing', 'AI segmentation', 'Analytics'],
    useCase: 'E-commerce marketing, email campaigns, customer segmentation',
    pros: ['Excellent e-commerce integration', 'AI segmentation', 'Good analytics'],
    cons: ['Expensive', 'E-commerce focused', 'Complex setup'],
    tags: ['Email Marketing', 'E-commerce', 'SMS'],
    imageUrl: 'https://cdn.worldvectorlogo.com/logos/klaviyo-1.svg'
  },
  {
    id: 'convertkit',
    name: 'ConvertKit',
    description: 'AI-powered email marketing for creators and bloggers',
    category: 'Sales & Marketing',
    subcategory: 'Email Marketing',
    url: 'https://convertkit.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Email automation', 'Creator tools', 'AI insights', 'Landing pages'],
    useCase: 'Creator marketing, email campaigns, audience building',
    pros: ['Creator-focused', 'Easy to use', 'Good automation'],
    cons: ['Limited features', 'Expensive', 'Basic AI'],
    tags: ['Email Marketing', 'Creators', 'Automation'],
    imageUrl: 'https://convertkit.com/wp-content/themes/convertkit-wordpress/dist/images/convertkit-logo.svg'
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'AI-powered marketing automation and CRM platform',
    category: 'Sales & Marketing',
    subcategory: 'Email Marketing',
    url: 'https://activecampaign.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Marketing automation', 'CRM', 'AI insights', 'Email marketing'],
    useCase: 'Marketing automation, customer journey mapping, email campaigns',
    pros: ['Comprehensive automation', 'Good CRM', 'AI insights'],
    cons: ['Complex setup', 'Expensive', 'Steep learning curve'],
    tags: ['Marketing Automation', 'CRM', 'Email Marketing'],
    imageUrl: 'https://www.activecampaign.com/themes/custom/activecampaign/images/logo.svg'
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI video generation platform with talking avatars and voice cloning',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://heygen.com',
    pricing: 'Paid',
    rating: 4.6,
    features: ['Talking avatars', 'Voice cloning', 'Video templates', 'Multi-language'],
    useCase: 'Marketing videos, presentations, educational content, UGC',
    pros: ['High-quality avatars', 'Voice cloning', 'Easy to use', 'Professional results'],
    cons: ['Expensive', 'Limited avatar customization', 'Watermark on free tier'],
    tags: ['Video Generation', 'AI Avatars', 'Voice Cloning', 'UGC'],
    imageUrl: 'https://assets-global.website-files.com/63f7b5c4b1f3f954af0e3d4a/63f7b5c4b1f3f9b6a40e3d7b_HeyGen%20Logo%20-%20Colored%20Text%20with%20Black%20Box.png'
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation platform with virtual avatars',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://synthesia.io',
    pricing: 'Paid',
    rating: 4.5,
    features: ['AI avatars', 'Video generation', 'Text-to-speech', 'Custom avatars'],
    useCase: 'Training videos, marketing content, educational videos',
    pros: ['High-quality avatars', 'Easy to use', 'Professional results'],
    cons: ['Expensive', 'Limited customization', 'Avatar-focused'],
    tags: ['Video Generation', 'AI Avatars', 'Training'],
    imageUrl: 'https://assets-global.website-files.com/63f7b5c4b1f3f954af0e3d4a/63f7b5c4b1f3f9b6a40e3d7b_Synthesia%20Logo%20-%20Colored%20Text%20with%20Black%20Box.png'
  },
  {
    id: 'pictory',
    name: 'Pictory',
    description: 'AI video creation from long-form content and blog posts',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://pictory.ai',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Blog to video', 'Auto-captioning', 'Video editing', 'Social media formats'],
    useCase: 'Content repurposing, social media videos, blog promotion',
    pros: ['Easy content repurposing', 'Auto-captioning', 'Multiple formats'],
    cons: ['Limited creative control', 'Quality varies', 'Template-based'],
    tags: ['Video Generation', 'Content Repurposing', 'Social Media'],
    imageUrl: 'https://pictory.ai/images/logo.svg'
  },
  {
    id: 'lumen5',
    name: 'Lumen5',
    description: 'AI-powered video creation from text content',
    category: 'Video & Visual',
    subcategory: 'Video Generation',
    url: 'https://lumen5.com',
    pricing: 'Freemium',
    rating: 4.2,
    features: ['Text to video', 'Video templates', 'Brand customization', 'Social media'],
    useCase: 'Marketing videos, social media content, blog promotion',
    pros: ['Easy to use', 'Good templates', 'Free tier available'],
    cons: ['Limited customization', 'Template-dependent', 'Basic features'],
    tags: ['Video Generation', 'Text to Video', 'Social Media'],
    imageUrl: 'https://lumen5.com/images/logo.svg'
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'AI-powered video editing and generation platform',
    category: 'Video & Visual',
    subcategory: 'Video Editing',
    url: 'https://runwayml.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['Video editing', 'AI generation', 'Motion graphics', 'Collaboration'],
    useCase: 'Video editing, motion graphics, AI video generation',
    pros: ['Professional features', 'AI integration', 'Collaboration tools'],
    cons: ['Steep learning curve', 'Expensive', 'Complex'],
    tags: ['Video Editing', 'Motion Graphics', 'Professional'],
    imageUrl: 'https://runwayml.com/images/logo.svg'
  },
  {
    id: 'capcut',
    name: 'CapCut',
    description: 'Free video editing app with AI-powered features',
    category: 'Video & Visual',
    subcategory: 'Video Editing',
    url: 'https://capcut.com',
    pricing: 'Free',
    rating: 4.4,
    features: ['Video editing', 'AI effects', 'Templates', 'Music library'],
    useCase: 'Social media videos, short-form content, UGC creation',
    pros: ['Completely free', 'Easy to use', 'Good templates', 'AI effects'],
    cons: ['Limited advanced features', 'Mobile-focused', 'Watermark options'],
    tags: ['Video Editing', 'Free', 'Social Media', 'UGC'],
    imageUrl: 'https://lf16-web.tiktokcdn.com/obj/tiktok-web-common-sg/mtact/static/images/logo_144c91a.png'
  },
  {
    id: 'dall-e',
    name: 'DALL-E',
    description: 'OpenAI\'s AI image generation model',
    category: 'Video & Visual',
    subcategory: 'Image Generation',
    url: 'https://openai.com/dall-e-2',
    pricing: 'Paid',
    rating: 4.5,
    features: ['Image generation', 'Image editing', 'Variations', 'High quality'],
    useCase: 'Marketing visuals, concept art, product mockups',
    pros: ['High quality', 'Easy to use', 'Good editing tools'],
    cons: ['Expensive', 'Limited artistic styles', 'OpenAI ecosystem'],
    tags: ['OpenAI', 'Image Generation', 'Editing'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/DALL%C2%B7E_icon.svg/1200px-DALL%C2%B7E_icon.svg.png'
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    description: 'AI image generation platform with custom models and training',
    category: 'Video & Visual',
    subcategory: 'Image Generation',
    url: 'https://leonardo.ai',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Custom models', 'Model training', 'High resolution', 'Commercial use'],
    useCase: 'Custom art styles, brand visuals, commercial projects',
    pros: ['Custom model training', 'Commercial licensing', 'High quality'],
    cons: ['Complex for beginners', 'Training costs', 'Limited free tier'],
    tags: ['Image Generation', 'Custom Models', 'Commercial Use']
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation model',
    category: 'Video & Visual',
    subcategory: 'Image Generation',
    url: 'https://stability.ai',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Open source', 'Local deployment', 'Custom training', 'High quality'],
    useCase: 'Custom image generation, research, commercial projects',
    pros: ['Open source', 'Local deployment', 'Customizable', 'Free'],
    cons: ['Technical setup required', 'Hardware intensive', 'Steep learning curve'],
    tags: ['Image Generation', 'Open Source', 'Local Deployment']
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Design platform with AI-powered features',
    category: 'Video & Visual',
    subcategory: 'Design',
    url: 'https://canva.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['AI design tools', 'Templates', 'Collaboration', 'Brand kit'],
    useCase: 'Graphic design, social media, presentations, marketing materials',
    pros: ['Easy to use', 'Extensive templates', 'AI features', 'Collaboration'],
    cons: ['Limited advanced features', 'Template-dependent', 'Can be expensive'],
    tags: ['Design', 'Templates', 'Collaboration', 'AI Design']
  },

  // Code & Development AI
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI-powered code completion and generation tool',
    category: 'Code & Development',
    subcategory: 'Code Generation',
    url: 'https://github.com/features/copilot',
    pricing: 'Paid',
    rating: 4.6,
    features: ['Code completion', 'Function generation', 'Documentation', 'Multi-language'],
    useCase: 'Software development, code generation, productivity',
    pros: ['Excellent code suggestions', 'Multi-language support', 'IDE integration'],
    cons: ['Expensive', 'Requires GitHub', 'Can suggest incorrect code'],
    tags: ['Code Generation', 'GitHub', 'IDE Integration'],
        imageUrl: 'https://github.githubassets.com/images/modules/site/features/copilot-icon-primary.svg'
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor with built-in AI assistance',
    category: 'Code & Development',
    subcategory: 'Code Editor',
    url: 'https://cursor.sh',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['AI chat', 'Code generation', 'Refactoring', 'VS Code compatible'],
    useCase: 'Software development, code editing, AI-assisted programming',
    pros: ['Built-in AI chat', 'VS Code compatible', 'Free tier'],
    cons: ['Newer tool', 'Limited features compared to VS Code'],
    tags: ['Code Editor', 'AI Chat', 'VS Code Compatible']
  },
  {
    id: 'replit',
    name: 'Replit',
    description: 'Online IDE with AI-powered code generation',
    category: 'Code & Development',
    subcategory: 'Online IDE',
    url: 'https://replit.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Online IDE', 'AI code generation', 'Collaboration', 'Deployment'],
    useCase: 'Online coding, education, prototyping, collaboration',
    pros: ['Free tier available', 'Easy collaboration', 'Built-in deployment'],
    cons: ['Limited resources on free tier', 'Internet dependent'],
    tags: ['Online IDE', 'Collaboration', 'Education']
  },

  // Business & Productivity AI
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'AI-powered workspace with writing and organization assistance',
    category: 'Business & Productivity',
    subcategory: 'Workspace',
    url: 'https://notion.so',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['AI writing', 'Task management', 'Knowledge base', 'Collaboration'],
    useCase: 'Project management, documentation, team collaboration',
    pros: ['Versatile workspace', 'Excellent AI features', 'Great collaboration'],
    cons: ['Can be complex', 'AI features are paid'],
    tags: ['Workspace', 'Collaboration', 'Documentation']
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'AI-powered project management and productivity platform',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://clickup.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Project management', 'AI writing', 'Automation', 'Time tracking'],
    useCase: 'Project management, team collaboration, task automation',
    pros: ['Comprehensive features', 'Good free tier', 'Excellent automation'],
    cons: ['Can be overwhelming', 'Complex setup'],
    tags: ['Project Management', 'Automation', 'Team Collaboration']
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'AI-powered automation platform connecting apps and services',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://zapier.com',
    pricing: 'Freemium',
    rating: 4.6,
    features: ['App integration', 'Workflow automation', 'AI assistance', 'Triggers'],
    useCase: 'Business automation, app integration, workflow optimization',
    pros: ['Extensive integrations', 'Powerful automation', 'AI assistance'],
    cons: ['Expensive for advanced features', 'Complex for beginners'],
    tags: ['Automation', 'Integrations', 'Workflows']
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: 'Visual automation platform with AI-powered workflows',
    category: 'Business & Productivity',
    subcategory: 'Automation',
    url: 'https://make.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Visual automation', 'App integration', 'AI assistance', 'Complex workflows'],
    useCase: 'Complex automation, data processing, business workflows',
    pros: ['Visual interface', 'Complex workflows', 'Good free tier'],
    cons: ['Steep learning curve', 'Can be expensive'],
    tags: ['Visual Automation', 'Complex Workflows', 'Data Processing']
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'AI-powered project management and team collaboration',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://asana.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Project management', 'AI insights', 'Team collaboration', 'Workflow automation'],
    useCase: 'Project management, team collaboration, workflow automation',
    pros: ['Excellent project management', 'Good collaboration', 'AI insights'],
    cons: ['Expensive', 'Complex for small teams', 'Limited AI features'],
    tags: ['Project Management', 'Collaboration', 'Workflow']
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project management with AI-powered automation',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://trello.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Kanban boards', 'AI automation', 'Team collaboration', 'Integrations'],
    useCase: 'Visual project management, task tracking, team collaboration',
    pros: ['Visual interface', 'Easy to use', 'Good integrations'],
    cons: ['Limited features', 'Basic AI', 'Can be expensive'],
    tags: ['Kanban', 'Visual Management', 'Collaboration']
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'AI-powered work operating system for teams',
    category: 'Business & Productivity',
    subcategory: 'Project Management',
    url: 'https://monday.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['Work OS', 'AI automation', 'Team collaboration', 'Custom workflows'],
    useCase: 'Team collaboration, project management, workflow automation',
    pros: ['Comprehensive platform', 'Good automation', 'Customizable'],
    cons: ['Expensive', 'Complex setup', 'Overwhelming features'],
    tags: ['Work OS', 'Collaboration', 'Automation']
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'AI-powered team communication and collaboration platform',
    category: 'Business & Productivity',
    subcategory: 'Workspace',
    url: 'https://slack.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Team messaging', 'AI search', 'App integrations', 'Voice calls'],
    useCase: 'Team communication, collaboration, workflow integration',
    pros: ['Excellent communication', 'Great integrations', 'AI search'],
    cons: ['Expensive', 'Can be distracting', 'Limited AI features'],
    tags: ['Communication', 'Collaboration', 'Integrations']
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'AI-powered collaboration platform with video conferencing',
    category: 'Business & Productivity',
    subcategory: 'Workspace',
    url: 'https://teams.microsoft.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Video conferencing', 'Team collaboration', 'AI features', 'Office integration'],
    useCase: 'Team collaboration, video meetings, document sharing',
    pros: ['Good video conferencing', 'Office integration', 'AI features'],
    cons: ['Complex interface', 'Microsoft ecosystem', 'Limited customization'],
    tags: ['Video Conferencing', 'Collaboration', 'Microsoft']
  },

  // Audio & Voice AI
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice synthesis and cloning platform',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    url: 'https://elevenlabs.io',
    pricing: 'Freemium',
    rating: 4.7,
    features: ['Voice cloning', 'Text-to-speech', 'Voice design', 'Multi-language'],
    useCase: 'Podcasts, audiobooks, video narration, voiceovers',
    pros: ['Exceptional voice quality', 'Voice cloning', 'Multiple languages', 'API access'],
    cons: ['Expensive for high usage', 'Ethical concerns', 'Limited free tier'],
    tags: ['Voice Synthesis', 'Voice Cloning', 'Text-to-Speech', 'High Quality'],
      imageUrl: 'https://pbs.twimg.com/profile_images/1645264656981254144/8BxZ5kY9_400x400.jpg'
  },
  {
    id: 'murph-ai',
    name: 'Murph AI',
    description: 'AI voice generator with studio-quality voices',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    url: 'https://murph.ai',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Studio voices', 'Voice cloning', 'Audio editing', 'Collaboration'],
    useCase: 'Podcasts, videos, presentations, voiceovers',
    pros: ['Studio-quality voices', 'Easy to use', 'Good collaboration'],
    cons: ['Limited free tier', 'Expensive', 'Voice selection'],
    tags: ['Voice Synthesis', 'Studio Quality', 'Voiceovers']
  },
  {
    id: 'play-ht',
    name: 'Play.ht',
    description: 'AI text-to-speech platform with natural voices',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    url: 'https://play.ht',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Natural voices', 'Voice cloning', 'Audio editing', 'Multiple formats'],
    useCase: 'Audiobooks, podcasts, videos, presentations',
    pros: ['Natural-sounding voices', 'Voice cloning', 'Multiple formats'],
    cons: ['Limited free tier', 'Quality varies', 'Expensive'],
    tags: ['Voice Synthesis', 'Natural Voices', 'Audiobooks']
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'Audio and video editing with AI voice generation',
    category: 'Audio & Voice',
    subcategory: 'Audio Editing',
    url: 'https://descript.com',
    pricing: 'Freemium',
    rating: 4.5,
    features: ['AI voice generation', 'Audio editing', 'Video editing', 'Transcription'],
    useCase: 'Podcasts, videos, presentations, content creation',
    pros: ['Excellent editing tools', 'AI voice features', 'Transcription', 'Easy to use'],
    cons: ['Expensive', 'Complex for beginners', 'Limited free tier'],
    tags: ['Audio Editing', 'AI Voice', 'Transcription', 'Video Editing']
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation platform with virtual avatars',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    url: 'https://synthesia.io',
    pricing: 'Paid',
    rating: 4.5,
    features: ['AI avatars', 'Video generation', 'Text-to-speech', 'Custom avatars'],
    useCase: 'Training videos, marketing content, educational videos',
    pros: ['High-quality avatars', 'Easy to use', 'Professional results'],
    cons: ['Expensive', 'Limited customization', 'Avatar-focused'],
    tags: ['Video Generation', 'AI Avatars', 'Training']
  },

  // UGC & Content Creation AI
  {
    id: 'influencer-ai',
    name: 'Influencer AI',
    description: 'AI-powered UGC content creation platform',
    category: 'UGC & Content',
    subcategory: 'Content Creation',
    url: 'https://influencer.ai',
    pricing: 'Paid',
    rating: 4.3,
    features: ['UGC generation', 'Content templates', 'Brand integration', 'Analytics'],
    useCase: 'UGC campaigns, influencer marketing, brand content',
    pros: ['UGC-focused', 'Brand integration', 'Analytics'],
    cons: ['Expensive', 'Limited customization', 'New platform'],
    tags: ['UGC', 'Content Creation', 'Influencer Marketing']
  },
  {
    id: 'content-ai',
    name: 'Content AI',
    description: 'AI-powered content creation for social media',
    category: 'UGC & Content',
    subcategory: 'Content Creation',
    url: 'https://content.ai',
    pricing: 'Freemium',
    rating: 4.2,
    features: ['Social media content', 'AI writing', 'Visual generation', 'Scheduling'],
    useCase: 'Social media management, content creation, brand marketing',
    pros: ['Social media focused', 'AI writing', 'Scheduling'],
    cons: ['Limited features', 'Quality varies', 'Basic templates'],
    tags: ['Social Media', 'Content Creation', 'AI Writing']
  },
  {
    id: 'hootsuite',
    name: 'Hootsuite',
    description: 'Social media management with AI content suggestions',
    category: 'UGC & Content',
    subcategory: 'Social Media',
    url: 'https://hootsuite.com',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Social media management', 'AI suggestions', 'Analytics', 'Scheduling'],
    useCase: 'Social media management, content scheduling, analytics',
    pros: ['Comprehensive platform', 'AI suggestions', 'Good analytics'],
    cons: ['Expensive', 'Complex setup', 'Limited AI features'],
    tags: ['Social Media', 'Management', 'Analytics']
  },
  {
    id: 'buffer',
    name: 'Buffer',
    description: 'Social media scheduling with AI content optimization',
    category: 'UGC & Content',
    subcategory: 'Social Media',
    url: 'https://buffer.com',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Social scheduling', 'AI optimization', 'Analytics', 'Team collaboration'],
    useCase: 'Social media scheduling, content optimization, team management',
    pros: ['Easy to use', 'AI optimization', 'Good collaboration'],
    cons: ['Limited features', 'Expensive', 'Basic AI'],
    tags: ['Social Media', 'Scheduling', 'Optimization']
  },

  // Research & Analysis AI
  {
    id: 'consensus',
    name: 'Consensus',
    description: 'AI-powered research platform for scientific papers and studies',
    category: 'Research & Analysis',
    subcategory: 'Academic Research',
    url: 'https://consensus.app',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['Scientific research', 'Paper analysis', 'Citation tracking', 'AI summaries'],
    useCase: 'Academic research, scientific analysis, evidence-based decisions',
    pros: ['Scientific focus', 'Evidence-based', 'Good summaries'],
    cons: ['Academic focus only', 'Limited general use'],
    tags: ['Academic Research', 'Scientific Papers', 'Evidence-Based']
  },
  {
    id: 'elicit',
    name: 'Elicit',
    description: 'AI research assistant for analyzing academic papers',
    category: 'Research & Analysis',
    subcategory: 'Academic Research',
    url: 'https://elicit.org',
    pricing: 'Freemium',
    rating: 4.3,
    features: ['Paper analysis', 'Research synthesis', 'Question answering', 'Citation analysis'],
    useCase: 'Academic research, literature reviews, evidence synthesis',
    pros: ['Excellent for research', 'Good synthesis', 'Free tier'],
    cons: ['Academic focus only', 'Limited features'],
    tags: ['Academic Research', 'Literature Review', 'Synthesis']
  },
  {
    id: 'tome',
    name: 'Tome',
    description: 'AI-powered presentation and storytelling platform',
    category: 'Research & Analysis',
    subcategory: 'Presentations',
    url: 'https://tome.app',
    pricing: 'Freemium',
    rating: 4.2,
    features: ['AI presentations', 'Storytelling', 'Visual generation', 'Collaboration'],
    useCase: 'Presentations, storytelling, visual communication',
    pros: ['Easy presentation creation', 'AI generation', 'Visual focus'],
    cons: ['Limited customization', 'Newer platform'],
    tags: ['Presentations', 'Storytelling', 'Visual Communication']
  },
  {
    id: 'gamma',
    name: 'Gamma',
    description: 'AI-powered presentation and document creation',
    category: 'Research & Analysis',
    subcategory: 'Presentations',
    url: 'https://gamma.app',
    pricing: 'Freemium',
    rating: 4.4,
    features: ['AI presentations', 'Document creation', 'Visual generation', 'Collaboration'],
    useCase: 'Presentations, documents, reports, visual content',
    pros: ['Easy creation', 'Good visuals', 'Collaboration'],
    cons: ['Limited customization', 'Template-dependent', 'New platform'],
    tags: ['Presentations', 'Documents', 'Visual Generation']
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    description: 'AI-powered presentation design platform',
    category: 'Research & Analysis',
    subcategory: 'Presentations',
    url: 'https://beautiful.ai',
    pricing: 'Paid',
    rating: 4.3,
    features: ['AI design', 'Smart templates', 'Real-time collaboration', 'Branding'],
    useCase: 'Professional presentations, sales decks, pitch decks',
    pros: ['Professional design', 'Smart templates', 'Collaboration'],
    cons: ['Expensive', 'Limited customization', 'Template-dependent'],
    tags: ['Presentations', 'Design', 'Professional']
  }
];
